#!/usr/bin/env tsx
/**
 * W2 — `hub-service`: control the hub as an OS service
 * (docs/windows-desktop-installer.md §8.2; plan §4.3/G2).
 *
 *   npx tsx scripts/service-cli.ts install [--data-dir hub-data] [--port 3000] [--device-port 5000]
 *       Emits + (on Windows) registers the service definition:
 *         - Windows: generated install-service.ps1 (sc.exe registration with
 *           auto-start + restart-on-crash) — run it as Administrator.
 *         - macOS:   io.hub.integration-hub.plist (launchd KeepAlive)
 *         - Linux:   integration-hub.service (systemd Restart=always)
 *       Templates live in packaging/; the generated file bakes in the
 *       install dir + data dir + env contract.
 *
 *   npx tsx scripts/service-cli.ts uninstall
 *       Emits the unregister commands (platform-matched).
 *
 *   npx tsx scripts/service-cli.ts status
 *       Shows whether the data dir exists and what the service would run.
 *
 * The service runs packages/server/src/service-cli.ts, which drives the
 * HubSupervisor (crash restart + health gate + rollback) with local defaults
 * (SQLite at <dataDir>/hub.sqlite, state at <dataDir>/state, logs in
 * <dataDir>/logs). Supervision semantics live in ONE place — this CLI only
 * decides how the OS keeps the supervisor process alive.
 */
import { parseArgs } from 'node:util';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const { values, positionals } = parseArgs({
  options: {
    'data-dir': { type: 'string', default: process.env.HUB_DATA_DIR ?? 'hub-data' },
    port: { type: 'string', default: process.env.PORT ?? '3000' },
    'device-port': { type: 'string', default: process.env.DEVICE_PORT ?? '5000' },
    'service-name': { type: 'string', default: 'integration-hub' },
    out: { type: 'string' },
  },
});
const command = positionals[0] ?? 'status';

const dataDir = resolve(values['data-dir']!);
const serviceName = values['service-name']!;
const packageRoot = fileURLToPath(new URL('../', import.meta.url));
const serviceEntry = join(packageRoot, 'packages', 'server', 'src', 'service-cli.ts');
const nodeExec = process.execPath;

const envLines = [
  `HUB_DATA_DIR=${dataDir}`,
  `PORT=${values.port}`,
  `DEVICE_PORT=${values['device-port']}`,
];

function windowsScript(): string {
  // sc.exe + recovery settings: auto-start, and restart the service when the
  // process dies (the supervisor itself handles crash-loop policy + rollback).
  const bin = `${nodeExec} --import tsx ${serviceEntry}`;
  const env = envLines.map((l) => `  \${k}: \${v}`).join('');
  return `# Generated by hub-service install — run as Administrator.
# Registers the Integration Hub local service (auto-start, restart on crash).
$name = '${serviceName}'
$bin  = '${bin}'
$envs = @{}
${envLines.split('\n').map((l) => l.trim()).filter(Boolean).map((l) => { const [k, ...rest] = l.split('='); return `$envs['${k}'] = '${rest.join('=')}'`; }).join('\n')}

sc.exe create $name binPath= "$bin" start= auto DisplayName= "Integration Hub (local)"
sc.exe description $name "Healthcare device integration hub - local edge service"
sc.exe failure $name reset= 86400 actions= restart/5000/restart/10000/restart/30000
Write-Host "Service '$name' registered. Start it:  Start-Service $name"
`;
}

function launchdPlist(): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>io.integration-hub.local</string>
  <key>ProgramArguments</key>
  <array>
    <string>${nodeExec}</string>
    <string>--import</string><string>tsx</string>
    <string>${serviceEntry}</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
${envLines.map((l) => { const [k, ...rest] = l.split('='); return `    <key>${k}</key><string>${rest.join('=')}</string>`; }).join('\n')}
  </dict>
  <key>KeepAlive</key><true/>
  <key>RunAtLoad</key><true/>
  <key>StandardOutPath</key><string>${join(dataDir, 'logs', 'service.log')}</string>
  <key>StandardErrorPath</key><string>${join(dataDir, 'logs', 'service.log')}</string>
</dict>
</plist>
`;
}

function systemdUnit(): string {
  return `[Unit]
Description=Integration Hub (local edge)
After=network.target

[Service]
Type=simple
ExecStart=${nodeExec} --import tsx ${serviceEntry}
WorkingDirectory=${packageRoot}
Environment=${envLines.join(' ')}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
`;
}

function writeOut(name: string, content: string): string {
  const target = values.out ?? join('packaging', 'generated', name);
  mkdirSync(resolve(target, '..'), { recursive: true });
  writeFileSync(target, content);
  return target;
}

switch (command) {
  case 'install': {
    if (!existsSync(serviceEntry)) {
      console.error(`service entry missing: ${serviceEntry}`);
      process.exit(1);
    }
    mkdirSync(join(dataDir, 'state'), { recursive: true });
    mkdirSync(join(dataDir, 'logs'), { recursive: true });
    console.log(`[hub-service] data dir ready: ${dataDir}`);
    if (process.platform === 'win32') {
      const file = writeOut('install-service.ps1', windowsScript());
      console.log(`[hub-service] generated ${file} — run it as Administrator to register the service.`);
    } else if (process.platform === 'darwin') {
      const file = writeOut('io.integration-hub.local.plist', launchdPlist());
      console.log(`[hub-service] generated ${file} — copy to ~/Library/LaunchAgents/ and: launchctl load -w <plist>`);
    } else {
      const file = writeOut('integration-hub.service', systemdUnit());
      console.log(`[hub-service] generated ${file} — copy to /etc/systemd/system/ and: systemctl enable --now integration-hub`);
    }
    break;
  }
  case 'uninstall': {
    if (process.platform === 'win32') {
      console.log(`[hub-service] run as Administrator:  sc.exe stop ${serviceName}; sc.exe delete ${serviceName}`);
    } else if (process.platform === 'darwin') {
      console.log(`[hub-service] launchctl bootout gui/$UID/io.integration-hub.local (then remove the plist)`);
    } else {
      console.log(`[hub-service] systemctl disable --now integration-hub (then remove the unit file)`);
    }
    console.log('[hub-service] data dir (SQLite + state + logs) is LEFT IN PLACE — back it up before deleting.');
    break;
  }
  case 'status': {
    console.log(`[hub-service] platform:   ${process.platform}`);
    console.log(`[hub-service] data dir:   ${dataDir} (${existsSync(dataDir) ? 'exists' : 'not created — run install'})`);
    console.log(`[hub-service] node:       ${nodeExec}`);
    console.log(`[hub-service] entry:      ${serviceEntry}`);
    console.log('[hub-service] the service runs service-cli.ts → HubSupervisor → hub (SQLite local mode).');
    break;
  }
  default:
    console.error(`unknown command: ${command} (install | uninstall | status)`);
    process.exit(2);
}
